/**
 * Screener Screen Definition & Catalog Registry
 * Supports built-in TradingView-style screens per asset class (Stocks, ETF, Bonds, MF)
 * and custom user-saved screens.
 */

import { AdvancedFilterState, DEFAULT_ADVANCED_FILTERS } from './filters';
import { ScreenerType } from './filter-config';

export interface ScreenDefinition {
  id: string;
  name: string;
  screenerType: ScreenerType;
  category: 'popular' | 'fundamental' | 'technical' | 'valuation' | 'custom';
  description: string;
  icon?: string;
  isBuiltin: boolean;
  filters: Partial<AdvancedFilterState>;
  quickPreset?: string;
  sortField?: string;
  sortDirection?: 'asc' | 'desc';
  columns?: string[];
}

export const BUILTIN_SCREENS: ScreenDefinition[] = [
  // =================== STOCKS ===================
  {
    id: 'stock_all',
    name: 'All stocks',
    screenerType: 'stocks',
    category: 'popular',
    description: 'Complete list of stocks by market cap',
    isBuiltin: true,
    quickPreset: 'all',
    filters: {},
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_most_capitalized',
    name: 'Most capitalized',
    screenerType: 'stocks',
    category: 'popular',
    description: 'Largest companies by market cap',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { marketCapTier: 'mega' },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_highest_net_income',
    name: 'Highest net income',
    screenerType: 'stocks',
    category: 'popular',
    description: 'Stocks raking in the cash with strong net margins',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { minNetMargin: 15 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_highest_cash',
    name: 'Highest cash',
    screenerType: 'stocks',
    category: 'popular',
    description: 'Companies with industry-leading balance sheet resilience',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { minRoce: 18 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_close_to_high_undervalued',
    name: 'Close to new-high and undervalued',
    screenerType: 'stocks',
    category: 'popular',
    description: 'Stocks breaking new local high backed by attractive valuation',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { near52WeekHigh: true, peMax: 25 },
    sortField: 'changePercent',
    sortDirection: 'desc',
  },
  {
    id: 'stock_healthy_growth_tech',
    name: 'Healthy growth technology stocks',
    screenerType: 'stocks',
    category: 'fundamental',
    description: 'Tech stocks growing quickly and not fueled by cash burning',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { sector: 'Technology', minNetMargin: 12 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_high_capital_efficiency',
    name: 'High capital efficiency stocks',
    screenerType: 'stocks',
    category: 'fundamental',
    description: 'Stocks with industry-high ROCE and capital efficiency ratios',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { minRoce: 22 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'stock_strong_small_caps',
    name: 'Strong performance small caps',
    screenerType: 'stocks',
    category: 'fundamental',
    description: 'Small-cap stocks with strong fundamentals and high momentum',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { marketCapTier: 'small', technicalRating: 'Buy' },
    sortField: 'changePercent',
    sortDirection: 'desc',
  },
  {
    id: 'stock_dividend_kings',
    name: 'Dividend kings',
    screenerType: 'stocks',
    category: 'valuation',
    description: 'Predictable and high dividend yield stocks for resilient portfolios',
    isBuiltin: true,
    quickPreset: 'dividend',
    filters: { minDividendYield: 2.5 },
    sortField: 'dividendYield',
    sortDirection: 'desc',
  },
  {
    id: 'stock_bullish_undervalued',
    name: 'Bullish and undervalued',
    screenerType: 'stocks',
    category: 'technical',
    description: 'Technically strong buy candidates trading below reasonable multiples',
    isBuiltin: true,
    quickPreset: 'momentum',
    filters: { technicalRating: 'Buy', peMax: 22 },
    sortField: 'changePercent',
    sortDirection: 'desc',
  },

  // =================== ETF ===================
  {
    id: 'etf_vault',
    name: 'ETF vault',
    screenerType: 'etf',
    category: 'popular',
    description: 'All exchange-traded funds ranked by assets under management',
    isBuiltin: true,
    quickPreset: 'all',
    filters: {},
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'etf_lowest_expense',
    name: 'Ultra-low cost index ETFs',
    screenerType: 'etf',
    category: 'popular',
    description: 'Institutional-grade ETFs with minimal expense ratios (<0.20%)',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { maxExpenseRatio: 0.20 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'etf_tech_growth',
    name: 'Technology & innovation ETFs',
    screenerType: 'etf',
    category: 'fundamental',
    description: 'Funds tracking semiconductors, cloud, AI, and digital ecosystems',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { focus: 'Technology' },
    sortField: 'changePercent',
    sortDirection: 'desc',
  },
  {
    id: 'etf_dividend_income',
    name: 'High yield dividend ETFs',
    screenerType: 'etf',
    category: 'valuation',
    description: 'Exchange-traded funds optimized for quarterly cash distributions',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { minDividendYield: 3.0 },
    sortField: 'dividendYield',
    sortDirection: 'desc',
  },
  {
    id: 'etf_commodity_gold',
    name: 'Gold & precious metals trackers',
    screenerType: 'etf',
    category: 'popular',
    description: 'Physical and synthetic bullion ETFs protecting purchasing power',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { assetClass: 'Commodity' },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },

  // =================== BONDS ===================
  {
    id: 'bond_all',
    name: 'All bonds',
    screenerType: 'bonds',
    category: 'popular',
    description: 'Fixed income instruments and debt securities',
    isBuiltin: true,
    quickPreset: 'all',
    filters: {},
    sortField: 'pe',
    sortDirection: 'desc',
  },
  {
    id: 'bond_sovereign',
    name: 'Sovereign & benchmark gilts',
    screenerType: 'bonds',
    category: 'popular',
    description: 'Government backed risk-free treasury debt across 5Y, 10Y, and 30Y tenors',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { issuerType: 'Sovereign' },
    sortField: 'pe',
    sortDirection: 'desc',
  },
  {
    id: 'bond_aaa_corporate',
    name: 'AAA prime corporate bonds',
    screenerType: 'bonds',
    category: 'fundamental',
    description: 'Highest credit rating corporate paper with attractive spread over G-Sec',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { creditRating: 'AAA' },
    sortField: 'pe',
    sortDirection: 'desc',
  },

  // =================== MUTUAL FUNDS ===================
  {
    id: 'mf_all',
    name: 'All mutual funds',
    screenerType: 'mf',
    category: 'popular',
    description: 'Comprehensive directory of equity, debt, and hybrid mutual fund schemes',
    isBuiltin: true,
    quickPreset: 'all',
    filters: {},
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
  {
    id: 'mf_consistent_large_cap',
    name: 'Top 5Y CAGR large cap funds',
    screenerType: 'mf',
    category: 'fundamental',
    description: 'Consistently outperforming tier-1 funds with >15% annualized 5Y CAGR',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { mfCategory: 'Equity Large Cap', minCagr5y: 15 },
    sortField: 'changePercent',
    sortDirection: 'desc',
  },
  {
    id: 'mf_direct_low_cost',
    name: 'Direct low-cost growth schemes',
    screenerType: 'mf',
    category: 'valuation',
    description: 'Direct plan mutual funds delivering maximum alpha via rock-bottom TER',
    isBuiltin: true,
    quickPreset: 'all',
    filters: { planType: 'Direct', maxExpenseRatio: 0.75 },
    sortField: 'marketCap',
    sortDirection: 'desc',
  },
];
